apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.applicationName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.applicationName }}
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
    - port: 4000
      targetPort: 4000
      protocol: TCP
      name: grpc
    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: metrics
  type: ClusterIP
  selector:
    app: {{ .Values.applicationName }}